---
version: 2
formats: all

build:
  os: ubuntu-22.04
  tools:
    # Keep version in sync with tox.ini (docs and gh-actions).
    python: "3.12"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
